exclude: |
  (?x)^(
    system/.+
    |user/\.icons/.+
    |user/\.config/nvim/lazy-lock\.json
    |user/\.config/systemd/user/.+
    |user/home/\.dmrc
    |desktop_screenshot\.png
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.19.1
    hooks:
      - id: stylua-github
        alias: stylua
        files: 'user/\.config/nvim/.+'

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/DetachHead/basedpyright
    rev: v1.12.4
    hooks:
      - id: basedpyright
