exclude: |
  (?x)^(
    system/.+
    |user/\.icons/.+
    |user/\.config/nvim/lazy-lock\.json
    |user/\.config/systemd/user/.+
    |user/home/\.dmrc
    |desktop_screenshot\.png
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-github
        alias: stylua
        files: ^user/\.config/nvim/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.15.0
    hooks:
      - id: basedpyright
