#!/usr/bin/bash

# Exit on errors
set -o errexit
set -o nounset
set -o pipefail

# Print commands as they are executed
set -o xtrace

dotfiles=$(dirname "$(realpath "$0")")

mkdir --verbose --parents \
    ~/.cache \
    ~/.config \
    ~/.local/bin \
    ~/.local/share \
    ~/.local/state \
    ~/Documents \
    ~/Downloads \
    ~/Pictures/Screenshots \
    ~/Music \
    ~/Videos \
    ~/archives \
    ~/projects \
    ~/repos

stow --verbose --dotfiles --dir "$dotfiles" --target ~ --stow home

tag='@generated by .dotfiles/install.sh'
if ! [ -e ~/.bashrc ] || ! grep --silent --fixed-strings "$tag" ~/.bashrc; then
    printf '\n# %s\nsource ~/.config/bash/bashrc.bash\n' "$tag" >> ~/.bashrc
fi

if ! pacman --query --check --quiet paru; then
    # Download the binary version to avoid compilation
    git clone https://aur.archlinux.org/paru-bin.git ~/repos/paru-bin
    pushd ~/repos/paru-bin
    makepkg --syncdeps --install
    popd
fi

paru -S --needed - < "$dotfiles/etc/packages.txt"
paru -S --needed - < "$dotfiles/etc/packages-aur.txt"
xargs pipx install < "$dotfiles/etc/packages-pypi.txt"
ya pkg install

systemctl --user enable \
    tldrcache.timer \
    hyprpaper.service \
    hypridle.service \
    waybar.service \
    gcr-ssh-agent.socket
