[tool.basedpyright]
include = [
    'install/',
    'user/.config/qtile',
    'user/.local/bin',
]
# The default value excludes '**/.*', which prevents files in 'user/.config' and
# 'user/.local/bin' from being type checked
exclude = [
    '**/__pycache__',
    '**/.venv',
    '**/.git',
]
extraPaths = ['/usr/lib/python3.12/site-packages/']  # Use system python
typeCheckingMode = 'standard'
pythonVersion = '3.12'
pythonPlatform = 'Linux'
deprecateTypingAliases = true
reportConstantRedefinition = true
reportMatchNotExhaustive = true
reportMissingParameterType = true
reportIgnoreCommentWithoutRule = true
# Avoid "'indentifier' not exported from 'module'" errors, see
# https://github.com/microsoft/pyright/issues/2277#issuecomment-937468789
reportPrivateImportUsage = false


[tool.isort]
profile = 'black'
line_length = 110
skip_gitignore = true
known_third_party = ['libqtile']


[tool.black]
line-length = 110
target-version = ['py312']
skip-string-normalization = true
include = '''
(
    \.pyi?$
    |^user/\.config/qtile/.*\.py$
    |^user/\.local/bin/frequencymenu$
    |^user/\.local/bin/paths$
    |^user/\.local/bin/notes$
)
'''
