[tool.black]
line-length = 100
target-version = ["py311"]
include = '''
(
    \.pyi?$
    |^user/\.config/qtile/
    |^user/\.local/bin/frequencymenu$
    |^user/\.local/bin/powermenu$
    |^user/\.local/bin/notes$
)
'''
