[tool.basedpyright]
pythonVersion = '3.12'
reportUnusedCallResult = false
reportAny = false
typeCheckingMode = 'standard'
# Avoid "'indentifier' not exported from 'module'" errors, see
# https://github.com/microsoft/pyright/issues/2277#issuecomment-937468789
reportPrivateImportUsage = false


[tool.isort]
profile = 'black'
line_length = 110
skip_gitignore = true
known_third_party = ['libqtile']


[tool.black]
line-length = 110
target-version = ['py312']
skip-string-normalization = true
include = '''
(
    \.pyi?$
    |^user/\.config/qtile/.*\.py$
    |^user/\.local/bin/frequencymenu$
    |^user/\.local/bin/paths$
    |^user/\.local/bin/notes$
)
'''
