[tool.black]
line-length = 100
target-version = ["py311"]
include = '''
(
    \.pyi?$
    |\.config/qtile/
    |\.local/bin/frequencymenu
    |\.local/bin/powermenu
    |\.local/bin/notes
    |\.local/bin/notes
)
'''

extend-exclude = '''
(
    \.txt$
)
'''
