#!/bin/bash
# Installation script

# Symbolic links for config files
. ./symlinks

# Install packages
pacman -Syu && pacman -S --needed - < ./pkglist.txt

# enabling services
systemctl enable lightdm.service
systemctl enable NetworkManager.service

# X11 persistent keyboard layout
localectl set-x11-keymap latam