#!/bin/bash
# Installation script


# Symbolic links for config files
. ./symlinks

# git
git config --global core.excludesfile ~/.gitignore_global

# Install packages
pacman -Syu && pacman -S --needed - < ./pkglist.txt

# enabling services
systemctl enable lightdm.service
systemctl enable NetworkManager.service

# X11 persistent keyboard layout
localectl set-x11-keymap latam

# Especial directories
[ -d "$HOME/projects"] || mkdir "$HOME/projects"
[ -d "$HOME/bin"] || mkdir "$HOME/bin"
[ -d "$HOME/.local/bin"] || mkdir -p "$HOME/.local/bin"

