#!/bin/bash
# Create symlinks for the config files


title()
{
    echo
    echo "--------------------------"
    echo "Creating symbolic links..."
    echo "--------------------------"
    echo
}


symfiles()
{
    dir_path="$1"
    dest_dir_path="$2"

    shopt -s dotglob # Include hidden files in glob (*)

    for file_path in "$dir_path"/*
    do
        file_name=$(basename "$file_path")
        dest_path="$dest_dir_path/$file_name"

        # If file exists, ask to remove it
        if [ -e "$dest_path" ]
        then
            # if the symbolic link to this file alredy exists, skip it
            if [[ -L "$dest_path" && $(readlink -f "$dest_path" = "$file_path") ]]
            then
                continue
            else
                echo "==> WARNING: '$dest_path' alredy exist!"
            fi
        fi
        
        ln -s -f -i -v "$file_path" "$dest_path"
    done

    shopt -u dotglob # Disable hidden files in glob (*)
}

main()
{
    title

    DOTFILES="$HOME/.dotfiles"
    symfiles "$DOTFILES/home" "$HOME"

    # Create ~/.config if it doesn't exists
    [ -d "$HOME/.config" ] || mkdir "$HOME/.config"
    symfiles "$DOTFILES/.config" "$HOME/.config"
}

main