#!/bin/bash
# Create symlinks for the config files


title()
{
    echo
    echo "--------------------------"
    echo "Creating symbolic links..."
    echo "--------------------------"
    echo
}


symlink()
{
    ln -s "$1" "$2"
    echo ":: Created symlink '$1' -> '$2'"
}


symfiles()
{
    dir_path="$1"
    dest_dir_path="$2"

    shopt -s dotglob # Include hidden files in glob (*)

    for file_path in "$dir_path"/*
    do
        file_name=$(basename "$file_path")
        dest_path="$dest_dir_path/$file_name"

        # If file exists, ask to remove it
        if [[ -e $dest_path ]]
        then
            echo
            echo "==> WARNING: '$dest_path' alredy exist!"
            rm -i -v "$dest_path"
            [[ -e $dest_path ]] && continue
        fi
        symlink "$file_path" "$dest_path"
    done

    shopt -u dotglob # Disable hidden files in glob (*)
}

main()
{
    title
    symfiles "$DOTFILES/home" "$HOME"
    symfiles "$DOTFILES/.config" "$HOME/.config"
}

main