appname := 'notification-test-script'

default: reload test

watch:
    printf dunstrc | entr just

reload:
    dunstctl close-all
    dunstctl reload

test:
    @notify-send --app-name={{appname}} --hint int:value:12 --urgency=low 'Low Urgency' 'This is the body.'
    @notify-send --app-name={{appname}} --hint int:value:52 --urgency=normal 'Normal Urgency' 'This is the body.'
    @notify-send --app-name={{appname}} --hint int:value:100 --urgency=critical 'Critical Urgency' 'This is the body.'
    @notify-send --app-name={{appname}} --urgency=normal 'Test title' 'Without bar'
    @notify-send --app-name={{appname}} \
        --action=First='Lorem impsum' \
        --action=Second='Dolor sit amet' \
        --action=Third='Consectetur' \
        'Actions' 'Notification with actions and no bar.'
