#!/bin/bash

# Create symlinks for the config files

sym()
{
    ln -s ~/.dotfiles/$1 ~/$1
}

CONF='.config'

sym .bashrc
sym .gitconfig
sym .xprofile
sym  $CONF/kitty
sym  $CONF/neofetch
sym  $CONF/picom
sym  $CONF/qtile
