#!/bin/bash
# Some useful git repositories
# shellcheck source=/dev/null

repos_dir="$HOME/repos"

[ -d "$repos_dir" ] || mkdir "$repos_dir"


get_repo()
{
    git clone -C "$repos_dir" "$1"
}

cursor_theme()
{
    icons_home="$HOME/.local/share/icons"
    [ -d "$icons_home" ] || mkdir "$icons_home"

    get_repo 'https://github.com/vinceliuice/Qogir-icon-theme' && \
        . "$repos_dir"/Qogir-icon-theme/src/cursors/install.sh && \
        ln -s "$icons_home"/Qogir-cursors/cursors ~/.icons/default/cursors
}

cursor_theme
