#!/bin/bash
# Installation script
# shellcheck source=/dev/null

# Symbolic links for config files
. ~/.dotfiles/scripts/symlinks

# git
git config --global core.excludesfile ~/.gitignore_global

# Install packages
pacman -Syu && pacman -S --needed - < ~/.dotfiles/pkglist.txt

# enabling services
systemctl enable lightdm.service
systemctl enable NetworkManager.service
systemctl enable cpupower.service

# X11 persistent keyboard layout
localectl set-x11-keymap latam

# Especial git files
[ -f /usr/share/git/completion/git-completion.bash ] && cp /usr/share/git/completion/git-completion.bash ~/
[ -f /usr/share/git/completion/git-prompt.sh ] && cp /usr/share/git/completion/git-prompt.sh ~/

# Especial directories
[ -d "$HOME/projects" ] || mkdir "$HOME/projects"
[ -d "$HOME/bin" ] || mkdir "$HOME/bin"

# Additional config
. ~/.dotfiles/scripts/slick_greeter_config
. ~/.dotfiles/scripts/repos

