#!/bin/bash
# Installation script
# shellcheck source=/dev/null

if (( EUID != 0 )); then
    echo "This file needs to be run with root permissions."
    exit 1
fi

# Symbolic links for config files
~/.dotfiles/scripts/symlinks

# Install packages
pacman -Syu && pacman -S --needed - < ~/.dotfiles/pkglist.txt

# enabling services
systemctl enable lightdm.service
systemctl enable NetworkManager.service
systemctl enable cpupower.service

# Special configs
~/.dotfiles/scripts/slick_greeter_config
~/.dotfiles/scripts/repos

# X11 persistent keyboard layout
localectl set-x11-keymap latam

# git
git config --global core.excludesfile ~/.gitignore_global

[ -f /usr/share/git/completion/git-completion.bash ] && cp /usr/share/git/completion/git-completion.bash ~/
[ -f /usr/share/git/completion/git-prompt.sh ] && cp /usr/share/git/completion/git-prompt.sh ~/

# Especial directories
directories=(
    "projects"
    ".local/bin"
    "bin"
    "archives"
)

for directory in "${directories[@]}";
do
    [ -d "$HOME/$directory" ] || mkdir "$HOME/$directory"
done
